create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  budget numeric not null,
  category text not null,
  result text,
  created_at timestamptz not null default now()
);

create table if not exists public.valuations (
  id bigint generated by default as identity primary key,
  purpose text not null,
  components text not null,
  condition_note text,
  usage_years integer not null,
  result text,
  created_at timestamptz not null default now()
);

create table if not exists public.part_listings (
  id bigint generated by default as identity primary key,
  title text not null,
  purpose text not null,
  part_type text not null,
  category text not null,
  price numeric not null,
  source text not null,
  source_site text not null,
  scraped_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.market_listings (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  purpose text not null,
  cpu text,
  gpu text,
  ram text,
  storage text,
  price numeric not null,
  condition text,
  source text not null,
  scraped_at date not null,
  created_at timestamptz not null default now()
);

alter table public.recommendations enable row level security;
alter table public.valuations enable row level security;
alter table public.part_listings enable row level security;
alter table public.market_listings enable row level security;

create policy if not exists "read recommendations"
on public.recommendations
for select
using (true);

create policy if not exists "insert recommendations"
on public.recommendations
for insert
with check (true);

create policy if not exists "read valuations"
on public.valuations
for select
using (true);

create policy if not exists "insert valuations"
on public.valuations
for insert
with check (true);

create policy if not exists "read part_listings"
on public.part_listings
for select
using (true);

create policy if not exists "insert part_listings"
on public.part_listings
for insert
with check (true);

create policy if not exists "delete part_listings"
on public.part_listings
for delete
using (true);

create policy if not exists "read market_listings"
on public.market_listings
for select
using (true);

create policy if not exists "insert market_listings"
on public.market_listings
for insert
with check (true);

create policy if not exists "delete market_listings"
on public.market_listings
for delete
using (true);
