const sources = [
  {
    name: "joongna-cpu",
    url: "https://web.joongna.com/search/cpu",
    purpose: "valuation",
    category: "cpu",
    partType: "cpu",
    keywords: ["cpu", "i3", "i5", "i7", "i9", "ryzen", "amd", "intel", "xeon", "epyc"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "CPU",
  },
  {
    name: "joongna-gpu",
    url: "https://web.joongna.com/search/gpu",
    purpose: "valuation",
    category: "gpu",
    partType: "gpu",
    keywords: ["gpu", "그래픽", "글카", "rtx", "gtx", "rx", "radeon", "geforce"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "GPU",
  },
  {
    name: "joongna-ram",
    url: "https://web.joongna.com/search/ram",
    purpose: "valuation",
    category: "ram",
    partType: "ram",
    keywords: ["ram", "메모리", "ddr4", "ddr5", "노트북램", "pc4", "pc5"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "RAM",
  },
  {
    name: "joongna-ssd",
    url: "https://web.joongna.com/search/ssd",
    purpose: "valuation",
    category: "ssd",
    partType: "ssd",
    keywords: ["ssd", "nvme", "m.2", "m2", "하드", "hdd", "스토리지"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "SSD",
  },
  {
    name: "joongna-motherboard",
    url: "https://web.joongna.com/search/메인보드",
    purpose: "valuation",
    category: "motherboard",
    partType: "motherboard",
    keywords: ["메인보드", "마더보드", "motherboard", "b550", "b650", "z690", "z790", "x570", "x670"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "메인보드",
  },
  {
    name: "joongna-psu",
    url: "https://web.joongna.com/search/파워서플라이",
    purpose: "valuation",
    category: "psu",
    partType: "psu",
    keywords: ["파워서플라이", "power supply", "컴퓨터파워", "psu", "브론즈", "골드", "플래티넘", "atx", "sfx", "모듈러"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "파워",
  },
  {
    name: "joongna-cooler",
    url: "https://web.joongna.com/search/쿨러",
    purpose: "valuation",
    category: "cooler",
    partType: "cooler",
    keywords: ["쿨러", "cooler", "수랭", "공랭", "aio", "팬", "리퀴드"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/product/"]',
    query: "쿨러",
  },
  {
    name: "bunjang-cpu",
    url: "https://m.bunjang.co.kr/search/products?q=cpu",
    purpose: "valuation",
    category: "cpu",
    partType: "cpu",
    keywords: ["cpu", "i3", "i5", "i7", "i9", "ryzen", "amd", "intel", "xeon", "epyc"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "CPU",
  },
  {
    name: "bunjang-gpu",
    url: "https://m.bunjang.co.kr/search/products?q=gpu",
    purpose: "valuation",
    category: "gpu",
    partType: "gpu",
    keywords: ["gpu", "그래픽", "글카", "rtx", "gtx", "rx", "radeon", "geforce"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "GPU",
  },
  {
    name: "bunjang-ram",
    url: "https://m.bunjang.co.kr/search/products?q=ram",
    purpose: "valuation",
    category: "ram",
    partType: "ram",
    keywords: ["ram", "메모리", "ddr4", "ddr5", "노트북램", "pc4", "pc5"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "RAM",
  },
  {
    name: "bunjang-ssd",
    url: "https://m.bunjang.co.kr/search/products?q=ssd",
    purpose: "valuation",
    category: "ssd",
    partType: "ssd",
    keywords: ["ssd", "nvme", "m.2", "m2", "하드", "hdd", "스토리지"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "SSD",
  },
  {
    name: "bunjang-motherboard",
    url: "https://m.bunjang.co.kr/search/products?q=%EB%A9%94%EC%9D%B8%EB%B3%B4%EB%93%9C",
    purpose: "valuation",
    category: "motherboard",
    partType: "motherboard",
    keywords: ["메인보드", "마더보드", "motherboard", "b550", "b650", "z690", "z790", "x570", "x670"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "메인보드",
  },
  {
    name: "bunjang-psu",
    url: "https://m.bunjang.co.kr/search/products?q=%ED%8C%8C%EC%9B%8C%EC%84%9C%ED%94%8C%EB%9D%BC%EC%9D%B4",
    purpose: "valuation",
    category: "psu",
    partType: "psu",
    keywords: ["파워서플라이", "power supply", "컴퓨터파워", "psu", "브론즈", "골드", "플래티넘", "atx", "sfx", "모듈러"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "파워",
  },
  {
    name: "bunjang-cooler",
    url: "https://m.bunjang.co.kr/search/products?q=%EC%BF%A8%EB%9F%AC",
    purpose: "valuation",
    category: "cooler",
    partType: "cooler",
    keywords: ["쿨러", "cooler", "수랭", "공랭", "aio", "팬", "리퀴드"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: 'a[href*="/products/"]',
    query: "쿨러",
  },
  {
    name: "danawa-cpu",
    url: "https://search.danawa.com/dsearch.php?k1=cpu",
    purpose: "valuation",
    category: "cpu",
    partType: "cpu",
    keywords: ["cpu", "i3", "i5", "i7", "i9", "ryzen", "amd", "intel", "xeon", "epyc"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: "a",
    query: "CPU",
  },
  {
    name: "danawa-gpu",
    url: "https://search.danawa.com/dsearch.php?k1=gpu",
    purpose: "valuation",
    category: "gpu",
    partType: "gpu",
    keywords: ["gpu", "그래픽", "글카", "rtx", "gtx", "rx", "radeon", "geforce"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: "a",
    query: "GPU",
  },
  {
    name: "danawa-ram",
    url: "https://search.danawa.com/dsearch.php?k1=ram",
    purpose: "valuation",
    category: "ram",
    partType: "ram",
    keywords: ["ram", "메모리", "ddr4", "ddr5", "노트북램", "pc4", "pc5"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: "a",
    query: "RAM",
  },
  {
    name: "danawa-ssd",
    url: "https://search.danawa.com/dsearch.php?k1=ssd",
    purpose: "valuation",
    category: "ssd",
    partType: "ssd",
    keywords: ["ssd", "nvme", "m.2", "m2", "하드", "hdd", "스토리지"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: "a",
    query: "SSD",
  },
  {
    name: "danawa-motherboard",
    url: "https://search.danawa.com/dsearch.php?k1=%EB%A9%94%EC%9D%B8%EB%B3%B4%EB%93%9C",
    purpose: "valuation",
    category: "motherboard",
    partType: "motherboard",
    keywords: ["메인보드", "마더보드", "motherboard", "b550", "b650", "z690", "z790", "x570", "x670"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료", "파워레인저", "체인소맨", "키라키라", "메탈엽서", "엽서", "굿즈", "피규어", "넨도로이드", "아크릴", "포스터", "포토카드"],
    itemSelector: "a",
    query: "메인보드",
  },
  {
    name: "danawa-psu",
    url: "https://search.danawa.com/dsearch.php?k1=%ED%8C%8C%EC%9B%8C%EC%84%9C%ED%94%8C%EB%9D%BC%EC%9D%B4",
    purpose: "valuation",
    category: "psu",
    partType: "psu",
    keywords: ["파워서플라이", "power supply", "컴퓨터파워", "psu", "브론즈", "골드", "플래티넘", "atx", "sfx", "모듈러"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료"],
    itemSelector: "a",
    query: "파워",
  },
  {
    name: "danawa-cooler",
    url: "https://search.danawa.com/dsearch.php?k1=%EC%BF%A8%EB%9F%AC",
    purpose: "valuation",
    category: "cooler",
    partType: "cooler",
    keywords: ["쿨러", "cooler", "수랭", "공랭", "aio", "팬", "리퀴드"],
    blockedKeywords: ["리딤코드", "쿠폰", "게임코드", "대리", "교환", "거래완료"],
    itemSelector: "a",
    query: "쿨러",
  },
];

export default sources;